### ISSUE TITLE
Feature Analysis Panel does not correctly show prototypes

### ISSUE THREAD

**Issue by enauz** [JonStargaryen/gmlvq#2]
no prototypes are displayed at all with the settings:
`gmlvq = new GMLVQCore.Builder().numberOfEpochs(1000)
                                       .numberOfPrototypesPerClass(5)
                                       .dataPointRatioPerRound(0.8)
//                                       .costFunctionToOptimize(CostFunctionValue.CLASSIFICATION_ERROR)
                                       .buildAndShow(dataPoints, instances);`

show/hide causes IOOBE:
`Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Vector.elementData(Vector.java:734)
	at java.util.Vector.elementAt(Vector.java:477)
	at javax.swing.DefaultListModel.getElementAt(DefaultListModel.java:89)
	at weka.classifiers.functions.gmlvq.visualization.VisualizerMouseAdapter.mouseClicked(VisualizerMouseAdapter.java:70)`

**Comment by JonStargaryen** [comment]
'ArrayIndexOutOfBoundsException' arises when clicking 'show' with no element selected on the left and respectively for 'remove' with no element selected on the right

**Comment by cleberecht** [comment]
The prototypes were not initialized before the first update. When the prototypes are not updated, no data can be shown.

I have added the initialization of prototypes and matrix to the constructor of GMLVQCore and this should work now.
